services:
  app-x86_64:
    image: localhost:5550/ray:latest
    build:
      args:
        - BASE_IMAGE=rayproject/ray:2.45.0-py311-cpu
      context: .
      dockerfile: Dockerfile

  app-arm64:
    image: localhost:5550/ray:latest
    build:
      args:
        - BASE_IMAGE=rayproject/ray:2.45.0-py311-cpu-aarch64
      context: .
      dockerfile: Dockerfile
