# see https://github.com/ray-project/kuberay/tree/master/helm-chart/ray-cluster
# and https://docs.ray.io/en/latest/cluster/kubernetes/user-guides/config.html
image:
  repository: ray-registry:5000/ray
  tag: latest
  pullPolicy: IfNotPresent

head:
  # enable autoscaling
  # see https://docs.ray.io/en/latest/cluster/kubernetes/user-guides/configuring-autoscaling.html#kuberay-autoscaling-configurations
  enableInTreeAutoscaling: true
  containerEnv:
    # enable autoscaler v2
    # see https://docs.ray.io/en/latest/cluster/kubernetes/user-guides/configuring-autoscaling.html#autoscaler-v2-with-kuberay
    - name: RAY_enable_autoscaler_v2
      value: "1"
  rayStartParams:
    # Setting "num-cpus: 0" to avoid any Ray actors or tasks being scheduled on the Ray head Pod.
    num-cpus: "0"
  resources:
    limits:
      cpu: "1"
      memory: "2G"
    requests:
      cpu: "1"
      memory: "2G"

worker:
  # number of replicas to start with before autoscaler takes over
  replicas: 0
  minReplicas: 0
  maxReplicas: 10
  resources:
    limits:
      cpu: "2"
      memory: "2G"
    requests:
      cpu: "2"
      memory: "2G"
